import React, { useState, useEffect } from 'react';
import { collection, query, orderBy, limit, getDocs, where } from 'firebase/firestore';
import { db } from '../firebase';
import NovelCard from './NovelCard';

const genres = [
  'all', 'urban', 'action', 'war', 'realistic', 'history',
    'fantasy', 'horror', 'mystery', 'adventure', 'romance', 'sci-fi',
      'acg', 'games', 'lgbt+', 'teen', 'devotional', 'poetry', 'general', 'chereads'
      ];

      function Rankings() {
        const [topNovels, setTopNovels] = useState([]);
          const [selectedGenre, setSelectedGenre] = useState('all');
            const [loading, setLoading] = useState(true);

              useEffect(() => {
                  const fetchTopNovels = async () => {
                        try {
                                setLoading(true);
                                        let novelQuery;
                                                
                                                        if (selectedGenre === 'all') {
                                                                  novelQuery = query(
                                                                              collection(db, 'Novels'),
                                                                                          orderBy('Views', 'desc'),
                                                                                                      limit(20)
                                                                                                                );
                                                                                                                        } else {
                                                                                                                                  novelQuery = query(
                                                                                                                                              collection(db, 'Novels'),
                                                                                                                                                          where('genres', 'array-contains', selectedGenre),
                                                                                                                                                                      orderBy('Views', 'desc'),
                                                                                                                                                                                  limit(20)
                                                                                                                                                                                            );
                                                                                                                                                                                                    }

                                                                                                                                                                                                            const querySnapshot = await getDocs(novelQuery);
                                                                                                                                                                                                                    const novels = querySnapshot.docs.map(doc => ({
                                                                                                                                                                                                                              id: doc.id,
                                                                                                                                                                                                                                        ...doc.data()
                                                                                                                                                                                                                                                }));
                                                                                                                                                                                                                                                        setTopNovels(novels);
                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                      console.error('Error fetching top novels:', error);
                                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                  fetchTopNovels();
                                                                                                                                                                                                                                                                                                    }, [selectedGenre]);

                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                          <div className="max-w-7xl mx-auto px-4 py-8">
                                                                                                                                                                                                                                                                                                                <h1 className="text-3xl font-bold mb-8">Novel Rankings</h1>
                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                            <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium text-gray-700 mb-2">
                                                                                                                                                                                                                                                                                                                                              Select Genre:
                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                              <select
                                                                                                                                                                                                                                                                                                                                                                        value={selectedGenre}
                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setSelectedGenre(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                            className="block w-full max-w-xs rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                              {genres.map((genre) => (
                                                                                                                                                                                                                                                                                                                                                                                                                          <option key={genre} value={genre}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        {genre.charAt(0).toUpperCase() + genre.slice(1)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-center items-center h-64">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-500 border-t-transparent"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {topNovels.map((novel, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={novel.id} className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="absolute -left-4 -top-4 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold z-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {index + 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <NovelCard novel={novel} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Rankings;